- hosts: dockers
  remote_user: ubuntu 
  tasks:
  - name: Update and upgrade
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install apps
    become: yes
    become_method: sudo
    apt:
      name: "{{packages}}"
    vars:
      packages:
      - tree
      - htop
      - vim
  - name: Install Docker prerequisites     
    become: yes
    become_method: sudo
    apt:
      name: "{{docker_prerequisites}}"
    vars:
      docker_prerequisites:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
  - name: Download Docker apt-key
    become: yes
    become_method: sudo
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: ~/docker.gpg
  - name: Add apt-key
    become: yes
    become_method: sudo
    apt_key:
      file: ~/docker.gpg    
  - name: Add Docker repository
    become: yes
    become_method: sudo
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
  - name: Update Ubuntu
    become: yes
    become_method: sudo
    apt:
      update_cache: yes
  - name: Install Docker
    become: yes
    become_method: sudo
    apt:
      name: docker-ce
